#ifndef COMPUTEHASH_GLOBAL_H
#define COMPUTEHASH_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(COMPUTEHASH_LIBRARY)
#  define COMPUTEHASHSHARED_EXPORT Q_DECL_EXPORT
#else
#  define COMPUTEHASHSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // COMPUTEHASH_GLOBAL_H
